MODEL_PATH = "your_path_to/deepseek-r1-distill-qwen-14b-multi-cognitive-bias"
TEMPLATE = "deepseek-chat"

JAILRL_MODEL = "your_path_to/deepseek-r1-distill-qwen-14b-multi-cognitive-bias-0313"

ONE_API_BASE = "YOUR_API_BASE"
ONE_API_KEY = "YOUR_API_KEY"

OLLAMA_API_BASE = "YOUR_API_BASE"
OLLAMA_API_KEY = "YOUR_API_KEY"

OLLAMA_API_BASE_1 = "YOUR_API_BASE"
OLLAMA_API_KEY_1 = "YOUR_API_KEY"

OLLAMA_API_BASE_2 = "YOUR_API_BASE"
OLLAMA_API_KEY_2 = "YOUR_API_KEY"

OPENAI_API_BASE = "YOUR_API_BASE"
OPENAI_API_KEY = "YOUR_API_KEY"

DASHSCOPE_API_BASE = "YOUR_API_BASE"
DASHSCOPE_API_KEY = "YOUR_API_KEY"

DEEPSEEK_API_BASE = "YOUR_API_BASE"
DEEPSEEK_API_KEY = "YOUR_API_KEY"

SILICONFLOW_API_BASE = "YOUR_API_BASE"
SILICONFLOW_API_KEY = "YOUR_API_KEY"

VOLCENGINE_API_BASE = "YOUR_API_BASE"
VOLCENGINE_API_KEY = "YOUR_API_KEY"

NV_API_BASE = "YOUR_API_BASE"
NV_API_KEY = "YOUR_API_KEY"